SET @project_id := (SELECT id FROM projects WHERE custom_id = 'CN2305-1' LIMIT 1);

INSERT INTO materials (name, description, unit_price, unit, category, sku, project_id, is_active)
VALUES
('Kompaktni ustredna zakladni verze vc. panelu', 'EPS polozka BD Radimova', 68249.02, 'kus', 'eps', 'BD-RAD-001', @project_id, 1),
('Zarizeni dalkoveho prenosu vc. koordinace', 'EPS/ZDP polozka BD Radimova', 191350.00, 'kpl', 'zdp', 'BD-RAD-002', @project_id, 1),
('BS OPPO CZ-EPI dle DIN 14661', 'EPS polozka BD Radimova', 10287.25, 'kus', 'eps', 'BD-RAD-003', @project_id, 1),
('Externi zobrazovaci panel pro hasice', 'EPS polozka BD Radimova', 12447.87, 'kus', 'eps', 'BD-RAD-004', @project_id, 1),
('Klicovy trezor pozarni ochrany pro Prahu', 'EPS polozka BD Radimova', 24704.00, 'kus', 'eps', 'BD-RAD-005', @project_id, 1),
('Majak cerveny kryt IP65', 'EPS polozka BD Radimova', 2063.99, 'kus', 'eps', 'BD-RAD-006', @project_id, 1),
('Multisenzorovy hlasic', 'EPS polozka BD Radimova', 1580.69, 'kus', 'eps', 'BD-RAD-007', @project_id, 1),
('Paralelni opticka signalizace BX-UPI', 'EPS polozka BD Radimova', 718.15, 'kus', 'eps', 'BD-RAD-008', @project_id, 1),
('Tlacitkovy hlasic typu A cerveny', 'EPS polozka BD Radimova', 1764.30, 'kus', 'eps', 'BD-RAD-009', @project_id, 1),
('Modul BX-REL4', 'EPS polozka BD Radimova', 3339.55, 'kus', 'eps', 'BD-RAD-010', @project_id, 1),
('Modul BXI-2', 'EPS polozka BD Radimova', 2750.70, 'kus', 'eps', 'BD-RAD-011', @project_id, 1),
('Modul BXI-IM4', 'EPS polozka BD Radimova', 2611.52, 'kus', 'eps', 'BD-RAD-012', @project_id, 1),
('Modul BX-IOM', 'EPS polozka BD Radimova', 2517.58, 'kus', 'eps', 'BD-RAD-013', @project_id, 1),
('Modul BX-AIM', 'EPS polozka BD Radimova', 2440.72, 'kus', 'eps', 'BD-RAD-014', @project_id, 1),
('Kompaktni zdroj BE-PSE01', 'EPS polozka BD Radimova', 10801.89, 'kus', 'eps', 'BD-RAD-015', @project_id, 1),
('SD karta 4GB pro B8-MCU-B9-BCU', 'EPS polozka BD Radimova', 432.79, 'kus', 'eps', 'BD-RAD-016', @project_id, 1),
('Sirena cervena interierova IP21', 'EPS polozka BD Radimova', 1147.29, 'kus', 'eps', 'BD-RAD-017', @project_id, 1),
('Kombinovany detektor koure a teplot', 'EPS polozka BD Radimova', 506.92, 'kus', 'eps', 'BD-RAD-018', @project_id, 1),
('Linearni teplotni detektor', 'EPS polozka BD Radimova', 143.55, 'm', 'eps', 'BD-RAD-019', @project_id, 1),
('Kabel PBRS 2x2x0,8', 'Kabelaz BD Radimova', 30.22, 'm', 'k', 'BD-RAD-020', @project_id, 1),
('Kabel s funkcni odolnosti B2caS1D0 2x2x0,8', 'Kabelaz BD Radimova', 45.47, 'm', 'k', 'BD-RAD-021', @project_id, 1),
('Kabel s funkcni odolnosti B2caS1D0 4x2x0,8', 'Kabelaz BD Radimova', 65.32, 'm', 'k', 'BD-RAD-022', @project_id, 1),
('Kabel s funkcni odolnosti B2caS1D0 2x1,5', 'Kabelaz BD Radimova', 45.02, 'm', 'k', 'BD-RAD-023', @project_id, 1),
('Kabelove trasy s funkcni schopnosti min. 60min', 'Instalacni polozka BD Radimova', 20.00, 'ks', 'i', 'BD-RAD-024', @project_id, 1),
('Protipozarni instalacni krabice pro sdelovaci kabely', 'Instalacni polozka BD Radimova', 765.78, 'ks', 'i', 'BD-RAD-025', @project_id, 1),
('Trubka ohebna pr. 20, 750N vc. sekani drazek', 'Instalacni polozka BD Radimova', 97.45, 'm', 'i', 'BD-RAD-026', @project_id, 1),
('Prichytky pro standardni kabel', 'Instalacni polozka BD Radimova', 24.64, 'm', 'i', 'BD-RAD-027', @project_id, 1),
('Kniha EPS', 'Ostatni polozka BD Radimova', 430.00, 'ks', 'eps', 'BD-RAD-028', @project_id, 1),
('Komplexni zkousky vyhrazeneho PBZ', 'Ostatni polozka BD Radimova', 6250.00, 'kpl', 'o', 'BD-RAD-029', @project_id, 1),
('Oziveni', 'Ostatni polozka BD Radimova', 8750.00, 'kpl', 'o', 'BD-RAD-030', @project_id, 1),
('Uvedeni do provozu', 'Ostatni polozka BD Radimova', 8750.00, 'kpl', 'o', 'BD-RAD-031', @project_id, 1),
('Zaskoleni obsluhy', 'Ostatni polozka BD Radimova', 2500.00, 'kpl', 'o', 'BD-RAD-032', @project_id, 1),
('Drobny instalacni material', 'Ostatni polozka BD Radimova', 73800.00, 'kpl', 'o', 'BD-RAD-033', @project_id, 1),
('Stavebni pripomoc', 'Ostatni polozka BD Radimova', 212500.00, 'kpl', 'o', 'BD-RAD-034', @project_id, 1),
('Pruzy zdivem do pr. 50mm', 'BP polozka BD Radimova', 124000.00, 'kpl', 'bp', 'BD-RAD-035', @project_id, 1)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  description = VALUES(description),
  unit_price = VALUES(unit_price),
  unit = VALUES(unit),
  category = VALUES(category),
  project_id = VALUES(project_id),
  is_active = VALUES(is_active),
  updated_at = CURRENT_TIMESTAMP;
